logs_level: info
http_server:
  mode: debug
  host: localhost
  port: 8080
  maxHeaderBytes: 16384
  timeouts:
    idle: 5
    readHeader: 120
    read: 10
    write: 10
storage:
  connection_string: host=127.0.0.1 user=go password=go dbname=go sslmode=disable