app:
  logs_level: info
  secret_key: Hfgtyh4nd3f!
  token_name: gomarket_auth
  token_lifetime: 6
http_server:
  mode: debug
  address: 127.0.0.1:8082
  maxHeaderBytes: 16384
  timeouts:
    idle: 5
    readHeader: 120
    read: 10
    write: 10
storage:
  connection_string: host=127.0.0.1 user=go password=go dbname=go sslmode=disable
  salt: gomarket
accrual:
  address: "http://localhost:8080"