// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// Ctxinfo is an autogenerated mock type for the ctxinfo type
type Ctxinfo struct {
	mock.Mock
}

// GetUserIDFromCtx provides a mock function with given fields: c
func (_m *Ctxinfo) GetUserIDFromCtx(c *gin.Context) (int64, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIDFromCtx")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (int64, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) int64); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCtxinfo creates a new instance of Ctxinfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCtxinfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Ctxinfo {
	mock := &Ctxinfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
